# Generated by Django 3.1.7 on 2021-04-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('startdate', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(max_length=100, null=True)),
                ('tarifprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.providers')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(max_length=100, null=True)),
                ('categoryname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.category')),
                ('numbercode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.numbercodes')),
            ],
        ),
        migrations.AddField(
            model_name='numbercodes',
            name='providerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.providers'),
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealerName', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('startdate', models.CharField(max_length=100, null=True)),
                ('providername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.providers')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('clientsnumber', models.ManyToManyField(to='mobile_company.PhoneNumbers')),
            ],
        ),
    ]
