# Generated by Django 3.1.7 on 2021-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0002_auto_20210405_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='providers',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
