# Generated by Django 3.1.7 on 2021-04-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0003_auto_20210405_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
