# Generated by Django 3.1.7 on 2021-04-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0004_auto_20210405_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='clientsnumber',
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.customer'),
        ),
    ]
