# Generated by Django 3.1.7 on 2021-04-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0005_auto_20210408_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.phonenumbers')),
                ('numbercode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.numbercodes')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.tarif')),
            ],
        ),
    ]
