# Generated by Django 3.1.7 on 2021-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0008_auto_20210409_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
