# Generated by Django 3.1.7 on 2021-04-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0012_auto_20210421_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.phonenumbers'),
        ),
    ]
