# Generated by Django 3.2 on 2021-04-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0013_auto_20210421_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numbercodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_company.numbercodes'),
        ),
    ]
