# Generated by Django 3.2 on 2021-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0014_order_numbercodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numbercodes',
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
