# Generated by Django 3.2 on 2021-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_company', '0015_auto_20210430_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
